/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;
import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        String fileIn = args[0];
        String fileOut = args[1];
        String method = args[2];

        Bitmap image = new Bitmap(fileIn);
//        image.flipHoriz(fileOut);
        if(method.equals("flipHoriz")){
            System.out.println("made it to if");
            image.flipHoriz(fileOut);
        }
        if(method.equals("flipVert")){
            System.out.println("made it to if");
            image.flipVert(fileOut);
        }
        if(method.equals("tiedye")){
            System.out.println("made it to if");
            image.tiedye(fileOut);
        }
    }
    //https://alvinalexander.com/blog/post/java/open-read-image-file-java-imageio-class
}
