/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;
import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    //https://alvinalexander.com/blog/post/java/open-read-image-file-java-imageio-class

    public void JavaImageIOTest(){
        try{
            BufferedImage image = ImageIO.read(new File());
            
        }
        catch(Exception e){
            System.out.println("Something went weird.")
        }
    }

}
