/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;
import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println(args[0]);

        Bitmap blah = new Bitmap(args[0]);
        blah.args[2](agrs[1]);

        Bitmap oatmeal = new Bitmap("/Users/jamesdansie/codefellows/401/bitmap-transformer/src/main/resources/stuff.bmp");
        oatmeal.flipHoriz();
        oatmeal = new Bitmap("/Users/jamesdansie/codefellows/401/bitmap-transformer/src/main/resources/stuff.bmp");
        oatmeal.flipVert();
        oatmeal = new Bitmap("/Users/jamesdansie/codefellows/401/bitmap-transformer/src/main/resources/stuff.bmp");
        oatmeal.tiedye();
    }
    //https://alvinalexander.com/blog/post/java/open-read-image-file-java-imageio-class
}
